/**
 * whatsapp.js — WhatsApp Business Calls API client
 *
 * Provides helpers to:
 *   - Accept an incoming call (send SDP answer back to WhatsApp)
 *   - Terminate a call
 *   - Send a text message to a phone number
 *
 * Adapted from bugzy-voice/app/whatsapp-backend/services/whatsapp.js
 */

const axios = require('axios');
const logger = require('../utils/logger');

class WhatsAppService {
    constructor() {
        this.token = process.env.WHATSAPP_TOKEN;
        this.phoneId = process.env.WHATSAPP_PHONE_NUMBER_ID;
        this.apiVersion = 'v19.0';
        this.baseUrl = `https://graph.facebook.com/${this.apiVersion}`;

        if (!this.token || !this.phoneId) {
            logger.error('WhatsApp credentials missing — check WHATSAPP_TOKEN / WHATSAPP_PHONE_NUMBER_ID');
        }
    }

    /**
     * Make an authenticated request to the WhatsApp API.
     * @param {string} path  API path (relative to baseUrl/phoneId)
     * @param {object} data  Request body
     * @param {string} [method='POST']
     */
    async _sendRequest(path, data, method = 'POST') {
        const url = `${this.baseUrl}/${this.phoneId}/${path}`;
        logger.debug(`WhatsApp API ${method} ${path}`, { data: JSON.stringify(data).slice(0, 200) });

        try {
            const response = await axios({
                method,
                url,
                data,
                headers: {
                    Authorization: `Bearer ${this.token}`,
                    'Content-Type': 'application/json',
                },
                timeout: 10000,
            });
            logger.debug(`WhatsApp API response [${path}]`, { status: response.status });
            return response.data;
        } catch (err) {
            const status = err.response?.status;
            const detail = err.response?.data;
            logger.error(`WhatsApp API error [${path}]`, { status, detail: JSON.stringify(detail).slice(0, 200) });
            throw err;
        }
    }

    /**
     * Send the SDP answer to accept an incoming WhatsApp call.
     * @param {string} callId   WhatsApp call ID
     * @param {string} toPhone  Caller phone number
     * @param {string} sdpAnswer  WebRTC SDP answer generated by our PeerConnection
     */
    async sendAccept(callId, toPhone, sdpAnswer) {
        logger.info('Sending call accept (SDP answer)', { callId, toPhone });
        return this._sendRequest('calls', {
            messaging_product: 'whatsapp',
            call_id: callId,
            to: toPhone,
            action: 'accept',
            session: {
                sdp: sdpAnswer,
                sdp_type: 'answer',
            },
        });
    }

    /**
     * Send a pre-accept notification before we send the full SDP answer.
     * This is required by the WhatsApp Calls API.
     */
    async sendPreAccept(callId, toPhone) {
        logger.info('Sending call pre-accept', { callId, toPhone });
        return this._sendRequest('calls', {
            messaging_product: 'whatsapp',
            call_id: callId,
            to: toPhone,
            action: 'pre_accept',
            description: 'Ringing',
        });
    }

    /**
     * Terminate an active call.
     * @param {string} callId   WhatsApp call ID
     * @param {string} toPhone  Phone number
     */
    async sendTerminate(callId, toPhone, reason = 'completed') {
        logger.info('Sending call terminate', { callId, toPhone });
        return this._sendRequest('calls', {
            messaging_product: 'whatsapp',
            call_id: callId,
            to: toPhone,
            action: 'terminate',
            reason,
        });
    }

    /**
     * Send a simple text message.
     * @param {string} to       Recipient phone number
     * @param {string} message  Text to send
     */
    async sendTextMessage(to, message) {
        logger.info('Sending text message', { to, length: message.length });
        return this._sendRequest('messages', {
            messaging_product: 'whatsapp',
            to,
            type: 'text',
            text: { body: message },
        });
    }

    /**
     * Store the active callId for a phone number so we can terminate it later.
     * @param {string} phone  Phone number key
     * @param {string} callId WhatsApp call ID
     */
    storeCallId(phone, callId) {
        if (!this._activeCallIds) this._activeCallIds = {};
        this._activeCallIds[phone] = callId;
        logger.debug('Stored callId', { phone, callId });
    }

    getCallId(phone) {
        return this._activeCallIds?.[phone] || null;
    }

    clearCallId(phone) {
        if (this._activeCallIds) delete this._activeCallIds[phone];
    }
}

module.exports = new WhatsAppService();
