"""
Nodes package for the Bugzy chatbot agent.

This package contains all node functions organized by functionality:
- user_verification_nodes: User verification and basic info collection
- meal_plan_nodes: Meal plan generation and management
- exercise_plan_nodes: Exercise plan generation and management
- qna_nodes: Health, product, and post-plan Q&A handling
"""

# Import all node functions for easy access
from app.services.chatbot.bugzy_ams.nodes.user_verification_nodes import (
    verify_user_node,
    collect_age,
    collect_height,
    collect_weight,
    calculate_bmi_node,
    transition_to_snap,
    snap_image_analysis,
    transition_to_gut_coach,
    validate_input,
    handle_validated_input,
)

from app.services.chatbot.bugzy_ams.nodes.meal_plan_nodes import (
    collect_health_conditions,
    collect_medications,
    ask_existing_meal_plan_choice,
    load_existing_meal_plan_for_edit,
    collect_diet_preference,
    collect_cuisine_preference,
    collect_current_dishes,
    collect_allergies,
    collect_water_intake,
    collect_beverages,
    collect_supplements,
    collect_gut_health,
    collect_meal_goals,
    generate_all_remaining_meal_days,
    generate_meal_plan,  # This is the Day 1 meal plan function
    generate_meal_day2_plan,
    generate_meal_day3_plan,
    generate_meal_day4_plan,
    generate_meal_day5_plan,
    generate_meal_day6_plan,
    generate_meal_day7_plan,
    handle_meal_day1_review_choice,
    collect_meal_day1_changes,
    regenerate_meal_day1_plan,
    handle_meal_day1_revised_review,
    transition_to_exercise,
    ask_meal_plan_preference,
    voice_agent_promotion_meal,
)

from app.services.chatbot.bugzy_ams.nodes.exercise_plan_nodes import (
    collect_fitness_level,
    collect_activity_types,
    collect_exercise_frequency,
    collect_exercise_intensity,
    collect_session_duration,
    collect_sedentary_time,
    collect_exercise_goals,
    generate_all_remaining_exercise_days,
    generate_day1_plan,
    generate_day2_plan,
    generate_day3_plan,
    generate_day4_plan,
    generate_day5_plan,
    generate_day6_plan,
    generate_day7_plan,
    handle_day1_review_choice,
    collect_day1_changes,
    regenerate_day1_plan,
    handle_day1_revised_review,
    ask_exercise_plan_preference,
    ask_existing_exercise_plan_choice,
    load_existing_exercise_plan_for_edit,
    voice_agent_promotion_exercise,
)

from app.services.chatbot.bugzy_ams.nodes.qna_nodes import (
    health_qna_node,
    product_qna_node,
    post_plan_qna_node,
    resume_from_qna_node,
    is_contextual_product_question,
    extract_relevant_product_from_history,
    reformulate_with_gpt,
    reformulate_followup_fallback,
    is_user_providing_information,
    extract_health_conditions_intelligently,
    extract_allergies_intelligently,
    extract_medications_intelligently,
    extract_supplements_intelligently,
    extract_gut_health_intelligently,
    # Note: The following functions remain in agent.py for now
    handle_meal_edit_request,
    handle_exercise_edit_request,
    handle_meal_day_selection_for_edit,
    handle_exercise_day_selection_for_edit,
    collect_meal_day_edit_changes,
    collect_exercise_day_edit_changes,
)

__all__ = [
    # User verification nodes
    'verify_user_node',
    'collect_age',
    'collect_height',
    'collect_weight',
    'calculate_bmi_node',
    'transition_to_snap',
    'snap_image_analysis',
    'transition_to_gut_coach',
    'validate_input',
    'handle_validated_input',
    
    # Meal plan nodes
    'collect_health_conditions',
    'collect_medications',
    'ask_existing_meal_plan_choice',
    'load_existing_meal_plan_for_edit',
    'collect_diet_preference',
    'collect_cuisine_preference',
    'collect_current_dishes',
    'collect_allergies',
    'collect_water_intake',
    'collect_beverages',
    'collect_supplements',
    'collect_gut_health',
    'collect_meal_goals',
    'generate_all_remaining_meal_days',
    'generate_meal_plan',  # This is the Day 1 meal plan function
    'generate_meal_day2_plan',
    'generate_meal_day3_plan',
    'generate_meal_day4_plan',
    'generate_meal_day5_plan',
    'generate_meal_day6_plan',
    'generate_meal_day7_plan',
    'handle_meal_day1_review_choice',
    'collect_meal_day1_changes',
    'regenerate_meal_day1_plan',
    'handle_meal_day1_revised_review',
    'transition_to_exercise',
    'ask_meal_plan_preference',
    'voice_agent_promotion_meal',
    
    # Exercise plan nodes
    'collect_fitness_level',
    'collect_activity_types',
    'collect_exercise_frequency',
    'collect_exercise_intensity',
    'collect_session_duration',
    'collect_sedentary_time',
    'collect_exercise_goals',
    'generate_all_remaining_exercise_days',
    'generate_day1_plan',
    'generate_day2_plan',
    'generate_day3_plan',
    'generate_day4_plan',
    'generate_day5_plan',
    'generate_day6_plan',
    'generate_day7_plan',
    'handle_day1_review_choice',
    'collect_day1_changes',
    'regenerate_day1_plan',
    'handle_day1_revised_review',
    'ask_exercise_plan_preference',
    'ask_existing_exercise_plan_choice',
    'load_existing_exercise_plan_for_edit',
    'voice_agent_promotion_exercise',
    
    # QnA nodes
    'health_qna_node',
    'product_qna_node',
    'post_plan_qna_node',
    'resume_from_qna_node',
    'is_contextual_product_question',
    'extract_relevant_product_from_history',
    'reformulate_with_gpt',
    'reformulate_followup_fallback',
    'is_user_providing_information',
    'extract_health_conditions_intelligently',
    'extract_allergies_intelligently',
    'extract_medications_intelligently',
    'extract_supplements_intelligently',
    'extract_gut_health_intelligently',
    # Note: The following functions remain in agent.py for now
    'handle_meal_edit_request',
    'handle_exercise_edit_request',
    'handle_meal_day_selection_for_edit',
    'handle_exercise_day_selection_for_edit',
    'collect_meal_day_edit_changes',
    'collect_exercise_day_edit_changes',
]
